name: Add Workspace Label to Issues

on:
  issues:
    types: [opened]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'enhancement')
    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Install dependencies
        run: yarn install

      - name: Extract issue body and number
        run: |
          {
            echo "ISSUE_BODY<<EOF"
            echo "${{ github.event.issue.body }}"
            echo "EOF"
          } >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Add workspace label
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
        run: node ./scripts/add-workspace-label.js
